version: "3"
services:
  conditional:
    build: .
    container_name: conditional
    depends_on:
      - conditional-postgres
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./migrations:/opt/conditional/migrations
    develop:
      watch:
        - action: sync+restart
          path: ./conditional
          target: /opt/conditional/conditional
          ignore:
            - __pycache__
        - action: sync+restart
          path: ./config.py
          target: /opt/conditional/config.py
        - action: rebuild
          path: ./frontend
  conditional-postgres:
    image: docker.io/postgres
    container_name: conditional-postgres
    environment:
      POSTGRES_PASSWORD: fancypantspassword 
      POSTGRES_USER: conditional
      POSTGRES_DATABASE: conditional
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

