"""add time spent to major projects

Revision ID: 217b5842448c
Revises: e2673b9e9ea8
Create Date: 2026-02-21 16:45:10.780115

"""

# revision identifiers, used by Alembic.
revision = '217b5842448c'
down_revision = 'e2673b9e9ea8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major_projects', sa.Column('timeSpent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('major_projects', 'timeSpent')
    # ### end Alembic commands ###
