"""empty message

Revision ID: 218de3b34a6f
Revises: 9c57eb87e918
Create Date: 2016-09-07 23:39:18.246359

"""

# revision identifiers, used by Alembic.
revision = '218de3b34a6f'
down_revision = '9c57eb87e918'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freshman_accounts', sa.Column('signatures_missed', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freshman_accounts', 'signatures_missed')
    ### end Alembic commands ###
