"""add packet

Revision ID: 27b8305621f5
Revises: 05126dcdf40e
Create Date: 2025-09-10 09:36:50.644872

"""

# revision identifiers, used by Alembic.
revision = '27b8305621f5'
down_revision = '05126dcdf40e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freshman',
    sa.Column('rit_username', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('onfloor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('rit_username')
    )
    op.create_table('notification_subscriptions',
    sa.Column('member', sa.String(length=36), nullable=True),
    sa.Column('freshman_username', sa.String(length=10), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['freshman_username'], ['freshman.rit_username'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('packet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freshman_username', sa.String(length=10), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freshman_username'], ['freshman.rit_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_fresh',
    sa.Column('packet_id', sa.Integer(), nullable=False),
    sa.Column('freshman_username', sa.String(length=10), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freshman_username'], ['freshman.rit_username'], ),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet_id', 'freshman_username')
    )
    op.create_table('signature_misc',
    sa.Column('packet_id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet_id', 'member')
    )
    op.create_table('signature_upper',
    sa.Column('packet_id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=36), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('eboard', sa.String(length=12), nullable=True),
    sa.Column('active_rtp', sa.Boolean(), nullable=False),
    sa.Column('three_da', sa.Boolean(), nullable=False),
    sa.Column('webmaster', sa.Boolean(), nullable=False),
    sa.Column('c_m', sa.Boolean(), nullable=False),
    sa.Column('w_m', sa.Boolean(), nullable=False),
    sa.Column('drink_admin', sa.Boolean(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet_id', 'member')
    )
    with op.batch_alter_table('freshman_accounts', schema=None) as batch_op:
        batch_op.drop_column('real_signatures_missed')

    with op.batch_alter_table('freshman_eval_data', schema=None) as batch_op:
        batch_op.drop_column('real_signatures_missed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freshman_eval_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_signatures_missed', sa.INTEGER(), server_default=sa.text("'-1'::integer"), autoincrement=False, nullable=False))

    with op.batch_alter_table('freshman_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_signatures_missed', sa.INTEGER(), server_default=sa.text("'-1'::integer"), autoincrement=False, nullable=False))

    op.drop_table('signature_upper')
    op.drop_table('signature_misc')
    op.drop_table('signature_fresh')
    op.drop_table('packet')
    op.drop_table('notification_subscriptions')
    op.drop_table('freshman')
    # ### end Alembic commands ###
