"""add adhoc column to committee_meetings

Revision ID: 3f094d78df95
Revises: 5e8db174ce30
Create Date: 2026-09-30 02:03:08.999839

"""

# revision identifiers, used by Alembic.
revision = '3f094d78df95'
down_revision = '5e8db174ce30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committee_meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adhoc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committee_meetings', schema=None) as batch_op:
        batch_op.drop_column('adhoc')

    # ### end Alembic commands ###
