"""AI usage input for major projects

Revision ID: 4c0f1c4e006f
Revises: ce92a683ecf8
Create Date: 2026-09-06 22:35:09.349126

"""

# revision identifiers, used by Alembic.
revision = "4c0f1c4e006f"
down_revision = "ce92a683ecf8"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("major_projects", sa.Column("ai_usage", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("major_projects", "ai_usage")
    # ### end Alembic commands ###
