"""Fix ts host schema

Revision ID: 5e8db174ce30
Revises: ce92a683ecf8
Create Date: 2026-09-06 21:24:34.985494

"""

# revision identifiers, used by Alembic.
revision = '5e8db174ce30'
down_revision = 'ce92a683ecf8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freshman_seminar_host', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freshman_seminar_host_fid'), ['fid'], unique=False)
        batch_op.drop_constraint(batch_op.f('freshman_seminar_host_fid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'freshman_accounts', ['fid'], ['id'], ondelete='cascade')

    with op.batch_alter_table('member_seminar_host', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_seminar_host_uid'), ['uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_seminar_host', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_seminar_host_uid'))

    with op.batch_alter_table('freshman_seminar_host', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('freshman_seminar_host_fid_fkey'), 'freshman_accounts', ['fid'], ['id'])
        batch_op.drop_index(batch_op.f('ix_freshman_seminar_host_fid'))

    # ### end Alembic commands ###
