"""Add relation between Conditional and Eval

Revision ID: 6f6b843e2b8f
Revises: e72e5d4d71f2
Create Date: 2017-04-26 19:44:14.159135

"""

# revision identifiers, used by Alembic.
revision = '6f6b843e2b8f'
down_revision = 'e72e5d4d71f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditional', sa.Column('evaluation', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conditional', 'spring_evals', ['evaluation'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conditional', type_='foreignkey')
    op.drop_column('conditional', 'evaluation')
    ### end Alembic commands ###
