"""add_rit_username

Revision ID: 704962eabf9c
Revises: d1a06ab54211
Create Date: 2019-08-27 09:58:45.776217

"""

# revision identifiers, used by Alembic.
revision = '704962eabf9c'
down_revision = 'd1a06ab54211'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freshman_accounts', sa.Column('rit_username', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freshman_accounts', 'rit_username')
    # ### end Alembic commands ###
