"""empty message

Revision ID: 72444bd2437e
Revises: 217b5842448c
Create Date: 2026-02-28 17:15:54.028901

"""

# revision identifiers, used by Alembic.
revision = '72444bd2437e'
down_revision = '217b5842448c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_project_skills',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['major_projects.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('project_id', 'skill')
    )
    op.add_column('major_projects', sa.Column('tldr', sa.String(length=128), nullable=True))
    op.add_column('major_projects', sa.Column('timeSpent', sa.Text(), nullable=True))
    op.alter_column('major_projects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_projects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('major_projects', 'timeSpent')
    op.drop_column('major_projects', 'tldr')
    op.drop_table('major_project_skills')
    # ### end Alembic commands ###
