"""empty message

Revision ID: 8182939744c8
Revises: f1d08673b870
Create Date: 2026-03-01 10:04:50.175588

"""

# revision identifiers, used by Alembic.
revision = '8182939744c8'
down_revision = 'f1d08673b870'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_project_skills',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['major_projects.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('project_id', 'skill')
    )
    op.add_column('major_projects', sa.Column('tldr', sa.String(length=128), nullable=True))
    op.alter_column('major_projects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_projects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('major_projects', 'tldr')
    op.drop_table('major_project_skills')
    # ### end Alembic commands ###
