"""empty message

Revision ID: 82cdb94fc915
Revises: f1d08673b870
Create Date: 2026-03-01 10:19:20.002845

"""

# revision identifiers, used by Alembic.
revision = '82cdb94fc915'
down_revision = 'f1d08673b870'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major_projects', sa.Column('links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('major_projects', 'links')
    # ### end Alembic commands ###
