"""empty message

Revision ID: 95538b39976f
Revises: 6c4cf35d7c0c
Create Date: 2026-03-09 15:20:23.072283

"""

# revision identifiers, used by Alembic.
revision = '95538b39976f'
down_revision = '6c4cf35d7c0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major_projects', sa.Column('time_spent', sa.Text(), nullable=True))
    op.drop_column('major_projects', 'timeSpent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major_projects', sa.Column('timeSpent', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('major_projects', 'time_spent')
    # ### end Alembic commands ###
