"""empty message

Revision ID: 983d69afb7f8
Revises: 218de3b34a6f
Create Date: 2016-10-18 22:36:45.102164

"""

# revision identifiers, used by Alembic.
revision = '983d69afb7f8'
down_revision = '218de3b34a6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housing_evals')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_evals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.VARCHAR(length=32), nullable=False),
    sa.Column('social_attended', sa.TEXT(), nullable=False),
    sa.Column('social_hosted', sa.TEXT(), nullable=False),
    sa.Column('technical_attended', sa.TEXT(), nullable=False),
    sa.Column('technical_hosted', sa.TEXT(), nullable=False),
    sa.Column('projects', sa.TEXT(), nullable=False),
    sa.Column('comments', sa.TEXT(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
