"""remove_freshmen_project

Revision ID: 9ae8696179d0
Revises: d1a06ab54211
Create Date: 2019-08-27 10:01:24.459604

"""

# revision identifiers, used by Alembic.
revision = '9ae8696179d0'
down_revision = 'd1a06ab54211'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freshman_eval_data', 'freshman_project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freshman_eval_data', sa.Column('freshman_project', postgresql.ENUM('Pending', 'Passed', 'Failed', name='freshman_project_enum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
