"""empty message

Revision ID: ce92a683ecf8
Revises: 95538b39976f
Create Date: 2026-04-01 19:08:20.149992

"""

# revision identifiers, used by Alembic.
revision = 'ce92a683ecf8'
down_revision = '95538b39976f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freshman_seminar_host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('seminar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fid'], ['freshman_accounts.id'], ),
    sa.ForeignKeyConstraint(['seminar_id'], ['technical_seminars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_seminar_host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('seminar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seminar_id'], ['technical_seminars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_seminar_host')
    op.drop_table('freshman_seminar_host')
    # ### end Alembic commands ###
