"""empty message

Revision ID: e2673b9e9ea8
Revises: 7a3904cac24b
Create Date: 2026-02-21 13:10:18.957944

"""

# revision identifiers, used by Alembic.
revision = 'e2673b9e9ea8'
down_revision = '7a3904cac24b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_id_fk', 'major_project_skills', type_='foreignkey')
    op.create_foreign_key(None, 'major_project_skills', 'major_projects', ['project_id'], ['id'], ondelete='cascade')
    op.alter_column('major_projects', 'tldr',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_projects', 'tldr',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint(None, 'major_project_skills', type_='foreignkey')
    op.create_foreign_key('project_id_fk', 'major_project_skills', 'major_projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
