"""update db

Revision ID: e38beaf3e875
Revises: 757e18146d16
Create Date: 2026-02-03 12:12:11.451367

"""

# revision identifiers, used by Alembic.
revision = 'e38beaf3e875'
down_revision = '757e18146d16'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('member_batch_users_id_idx', table_name='member_batch_users')
    op.drop_table('member_batch_users')
    op.drop_index('freshman_batch_pulls_id_idx', table_name='freshman_batch_pulls')
    op.drop_table('freshman_batch_pulls')
    op.drop_index('member_batch_pulls_id_idx', table_name='member_batch_pulls')
    op.drop_table('member_batch_pulls')
    op.drop_index('freshman_batch_users_id_pkey', table_name='freshman_batch_users')
    op.drop_table('freshman_batch_users')
    op.drop_table('batch_conditions')
    op.alter_column('freshman_accounts', 'onfloor_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('freshman_accounts', 'rit_username',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('freshman_hm_attendance', 'attendance_status',
               existing_type=postgresql.ENUM('Attended', 'Excused', 'Absent', name='attendance_enum'),
               nullable=True)
    op.alter_column('member_hm_attendance', 'attendance_status',
               existing_type=postgresql.ENUM('Attended', 'Excused', 'Absent', name='attendance_enum'),
               nullable=True)
    op.drop_table('batch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_hm_attendance', 'attendance_status',
               existing_type=postgresql.ENUM('Attended', 'Excused', 'Absent', name='attendance_enum'),
               nullable=False)
    op.alter_column('freshman_hm_attendance', 'attendance_status',
               existing_type=postgresql.ENUM('Attended', 'Excused', 'Absent', name='attendance_enum'),
               nullable=False)
    op.alter_column('freshman_accounts', 'rit_username',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('freshman_accounts', 'onfloor_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_table('batch_conditions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', postgresql.ENUM('packet', 'seminar', 'committee', 'house', name='batch_ctype_enum'), autoincrement=False, nullable=False),
    sa.Column('comparison', postgresql.ENUM('less', 'equal', 'greater', name='batch_comparison'), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name='batch_conditions_fk'),
    sa.PrimaryKeyConstraint('id', name='batch_conditions_pkey')
    )
    op.create_table('freshman_batch_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name='freshman_batch_users_fk'),
    sa.ForeignKeyConstraint(['fid'], ['freshman_accounts.id'], name='freshman_batch_users_fk_1'),
    sa.PrimaryKeyConstraint('id', name='freshman_batch_users_pkey')
    )
    op.create_index('freshman_batch_users_id_pkey', 'freshman_batch_users', ['id'], unique=True)
    op.create_table('batch',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('batch_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='batch_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('member_batch_pulls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('puller', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='member_batch_pulls_pkey')
    )
    op.create_index('member_batch_pulls_id_idx', 'member_batch_pulls', ['id'], unique=True)
    op.create_table('freshman_batch_pulls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('puller', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fid'], ['freshman_accounts.id'], name='freshman_batch_pulls_fk_1'),
    sa.PrimaryKeyConstraint('id', name='freshman_batch_pulls_pkey')
    )
    op.create_index('freshman_batch_pulls_id_idx', 'freshman_batch_pulls', ['id'], unique=True)
    op.create_table('member_batch_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name='member_batch_users_fk'),
    sa.PrimaryKeyConstraint('id', name='member_batch_users_pkey')
    )
    op.create_index('member_batch_users_id_idx', 'member_batch_users', ['id'], unique=False)
    # ### end Alembic commands ###
