"""Add Approved Column for CM and TS

Revision ID: e72e5d4d71f2
Revises: 65943c537c84
Create Date: 2017-01-21 16:28:25.498369

"""

# revision identifiers, used by Alembic.
revision = 'e72e5d4d71f2'
down_revision = '65943c537c84'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directorship_meetings', sa.Column('approved', sa.Boolean(), server_default=sa.sql.expression.true(), nullable=False))
    op.add_column('technical_seminars', sa.Column('approved', sa.Boolean(), server_default=sa.sql.expression.true(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directorship_meetings', 'approved')
    op.drop_column('technical_seminars', 'approved')
    ### end Alembic commands ###
