"""Set uid and fid as table indicies

Revision ID: f1d08673b870
Revises: 7a3904cac24b
Create Date: 2026-02-17 15:02:08.721333

"""

# revision identifiers, used by Alembic.
revision = 'f1d08673b870'
down_revision = '7a3904cac24b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_freshman_committee_attendance_fid'), 'freshman_committee_attendance', ['fid'], unique=False)
    op.create_index(op.f('ix_freshman_hm_attendance_fid'), 'freshman_hm_attendance', ['fid'], unique=False)
    op.create_index(op.f('ix_freshman_seminar_attendance_fid'), 'freshman_seminar_attendance', ['fid'], unique=False)
    op.create_index(op.f('ix_major_projects_uid'), 'major_projects', ['uid'], unique=False)
    op.create_index(op.f('ix_member_committee_attendance_uid'), 'member_committee_attendance', ['uid'], unique=False)
    op.create_index(op.f('ix_member_hm_attendance_uid'), 'member_hm_attendance', ['uid'], unique=False)
    op.create_index(op.f('ix_member_seminar_attendance_uid'), 'member_seminar_attendance', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_seminar_attendance_uid'), table_name='member_seminar_attendance')
    op.drop_index(op.f('ix_member_hm_attendance_uid'), table_name='member_hm_attendance')
    op.drop_index(op.f('ix_member_committee_attendance_uid'), table_name='member_committee_attendance')
    op.drop_index(op.f('ix_major_projects_uid'), table_name='major_projects')
    op.drop_index(op.f('ix_freshman_seminar_attendance_fid'), table_name='freshman_seminar_attendance')
    op.drop_index(op.f('ix_freshman_hm_attendance_fid'), table_name='freshman_hm_attendance')
    op.drop_index(op.f('ix_freshman_committee_attendance_fid'), table_name='freshman_committee_attendance')
    # ### end Alembic commands ###
